### ISSUE TITLE
Error on MacOS: signal: killed

### ISSUE THREAD

**Issue by sticreations** [go-opencv/go-opencv#103]
I am trying to run the hellocv example, but i am getting the error message : 

> signal: killed

I installed opencv via homebrew in version 2.4.13.2

Any ideas what i am missing?

**Comment by sticreations** [comment]
Alright, after a lot of research I found out that this is a Mac related Problem which exists since the new Update.  
So this Issue will be a wontfix.

**Comment by ralphgj** [comment]
I updated the go version to 1.8.1 and then it was ok.
