### ISSUE TITLE
add/wrap more APIs

### ISSUE THREAD

**Issue by zx9597446** [go-opencv/go-opencv#47]
@lazywei I'm not familar with opencv APIs yet,  I think I need these APIs(from tutorial), it would be great if you add/wrap more APIs, thanks!
1. threshold
   Applies a fixed-level threshold to each array element.
   double threshold(InputArray src, OutputArray dst, double thresh, double maxval, int type)
2. findContours
   Finds contours in a binary image.
   C++: void findContours(InputOutputArray image, OutputArrayOfArrays contours, OutputArray hierarchy, int mode, int method, Point offset=Point())
   C++: void findContours(InputOutputArray image, OutputArrayOfArrays contours, int mode, int method, Point offset=Point())
3. drawContours
   Draws contours outlines or filled contours.
   C++: void drawContours(InputOutputArray image, InputArrayOfArrays contours, int contourIdx, const Scalar& color, int thickness=1, int lineType=8, InputArray hierarchy=noArray(), int maxLevel=INT_MAX, Point offset=Point() )

**Comment by lazywei** [comment]
received and thanks @zx9597446 
I'll work on this when I'm more available.
