### ISSUE TITLE
Package opencv was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by jabrena** [go-opencv/go-opencv#57]
Hi,

I am newbie Go developer and I am trying to test your project but when I try to execute:

``` go
go run hellocv.go
```

I receive the following message:

``` shell
exec: "pkg-config": executable file not found in $PATH
```

How to fix it?

**Comment by jabrena** [comment]
I fixed installing the package:

apt-get install pkg-config

but now, I receive:

``` shell

# pkg-config --cflags opencv opencv opencv opencv opencv opencv opencv
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
exit status 1

```

**Comment by jabrena** [comment]
I have found: opencv.pc here:

``` 
apt-file search opencv.pc
libopencv-dev: /usr/lib/arm-linux-gnueabi/pkgconfig/opencv.pc
``` 

How to add the directory into PKG_CONFIG_PATH?

```
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
```

**Comment by lazywei** [comment]
How did you install your opencv? If you are on Ubuntu, maybe you could try this: https://help.ubuntu.com/community/OpenCV

**Comment by jvasquezz** [comment]
Im getting this same error  but on OS X El Capitan

**Comment by Majonsi** [comment]
try:
` sudo apt-get install libopencv-dev`
it worked for me

**Comment by anandshanbhag** [comment]
I had similar issue on my macOS Sierra and I did following things to resolve the issue.

`brew tap homebrew/science
brew install opencv`

Once I ran the two commands mentioned above the "opencv.pc" (shortcut) got created at "/usr/local/lib/pkgconfig/" folder.  Actual path of opencv libraries are at "/usr/local/Cellar/opencv/2.4.13.2/lib/" 

To test go-opencv sample program do do following thing as mentioned in the home page of go-opencv;
```
go get github.com/lazywei/go-opencv
cd $GOPATH/src/github.com/lazywei/go-opencv/samples
go run hellocv.go
```

**Comment by yc67** [comment]
I also changed my PKG_CONFIG_PATH to the directory that contains my opencv.pc file, however the same error message still continues to pop up. Is there a solution to it yet? Thanks!

**Comment by bronzenose** [comment]
The [build instructions for opencv](http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html) give the answer:

> 8. To install libraries, execute the following command from build directory
> `sudo make install`

Perhaps others stopped at step 7 like I did.

**Comment by minghaoxi** [comment]
https://prateekvjoshi.com/2013/10/18/package-opencv-not-found-lets-find-it/

sudo make install
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

this can fix your problem.

**Comment by jabrena** [comment]
Thanks.

**Comment by Kabariya** [comment]
In member function ‘void cv::EigenvalueDecomposition::compute(cv::InputArray, bool)’:
cc1plus: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]

i am getting this when i am installing opencv

**Comment by Eyshika** [comment]
I am trying to install opencv3.2.0 using `sudo apt-get libopencv python`. It runs perfectly but couldnt find opencv in pkg-config or even in python, also am not sure if its specifically installing 3.2.0 version or not. i dont want to install it from source.

**Comment by abhishekbaghel** [comment]
> try:
> `sudo apt-get install libopencv-dev`
> it worked for me

Worked for me as well :)

**Comment by theLastRaider** [comment]
>  `sudo apt-get install libopencv-dev`

this worked for me too

**Comment by kokun66** [comment]
that would install a difference version?

**Comment by 111120195** [comment]
> try:
> ` sudo apt-get install libopencv-dev`
> it worked for me

it worked for me too! thanks!

**Comment by ghost** [comment]
I have tried everything, did someone fixed it with another approach?

**Comment by chophy** [comment]
try:
sudo apt-get install libopencv-dev
it worked for me

it worked for me too! thanks!

**Comment by ebtesam01** [comment]
> try:
> ` sudo apt-get install libopencv-dev`
> it worked for me

thanks, it worked for me too

**Comment by Amither111** [comment]
> try:
> ` sudo apt-get install libopencv-dev`
> it worked for me

I tried，and it worked. But the version is wrong. 
What I installed is opencv3.4.x, but
`pkg-config --modversion opencv`
`2.4.9.1`
why??

**Comment by ghost** [comment]
> try:
> ` sudo apt-get install libopencv-dev`
> it worked for me

greate,worked for me too.

**Comment by Alihamdy2496** [comment]
apt-get install libopencv-dev
worked for me but the python binding isn't working , when i run this 

     python -c "import cv2; print(cv2.__version__)"
i get this

     ImportError: No module named cv2
